# Generated by Django 4.2.1 on 2023-06-02 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[('id', models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False,
                verbose_name='ID')),
                ('minecraft_username', models.CharField(
                    max_length=100)),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL)),],),]
