baseURL = 'https://container-minecraft-app.pages.dev/'
languageCode = 'en-us'
title = 'Container Minecraft App'
paginate = 10
disableKinds = ['taxonomy', 'term']
enableRobotsTXT = true
googleAnalytics = 'G-1DRW60QS2W'

[author]
name = "Michael Shogren"

[build]
  writeStats = true

[privacy]
  [privacy.googleAnalytics]
    respectDoNotTrack = true
    useSessionStorage = true

[menu]
  [[menu.main]]
    name = 'Blog'
    url = '/blog'
    weight = 1
  [[menu.main]]
    name = 'Github'
    url = 'https://github.com/mshogren/container-minecraft-app'
    weight = 2

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'node_modules/purecss/build'
    target = 'assets/css/purecss'

[mediaTypes]
  [mediaTypes.'text/pages.dev']
    delimiter = ''
    suffixes = 'headers'

[outputFormats]
  [outputFormats.HEADERS]
    baseName = '_'
    isPlainText = true
    mediaType = 'text/pages.dev'
    notAlternative = true

[outputs]
  home = ['HTML', 'RSS', 'HEADERS']

[markup]
  [markup.highlight]
    noClasses = false
    style = 'solarized-dark256'
    tabWidth = 2
