name: API CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: python

    steps:
      - uses: actions/checkout@v2

      - name: install pipenv
        run: pip install pipenv
          
      - name: install dependencies 
        run: pipenv install
        working-directory: ./api

      - name: lint with pylint
        run: pylint
        working-directory: ./api
