name: API CI

on:
  push:
    branches: [ master ]
    paths:
      - 'api/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'api/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3

      - uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # tag=v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: install dependencies
        run: npm ci

      - name: install pipenv
        run: pip install pipenv

      - uses: actions/setup-python@21c0493ecfd34b1217f0a90ec19a327f3cc0a048 # tag=v3
        with:
          python-version: '3.9'
          cache: 'pipenv'

      - name: install dependencies
        run: pipenv install --dev --deploy

      - name: lint with pylint
        run: pipenv run pylint *.py **/*.py

      - name: lint the graphql schema
        run: pipenv run strawberry export-schema main | npx graphql-schema-linter -s -e relay-page-info-spec,enum-values-have-descriptions

      - name: test with pytest
        run: pipenv run pytest
