name: API CI

on:
  push:
    branches: [ master ]
    paths:
      - 'api/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'api/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    steps:
      - uses: actions/checkout@v2
      
      - name: install pipenv
        run: pip install pipenv
          
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pipenv'

      - name: install dependencies 
        run: pipenv install --dev --deploy

      - name: lint with pylint
        run: pipenv run pylint ../**/*.py
      
      - name: test with pytest
        run: pipenv run pytest
