name: API CI

on:
  push:
    branches: [ master ]
    paths:
      - 'api/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'api/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3

      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: install dependencies
        run: npm ci

      - name: install pipenv
        run: pip install pipenv

      - uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4
        with:
          python-version: '3.9'
          cache: 'pipenv'

      - name: install dependencies
        run: pipenv install --dev --deploy

      - name: lint with pylint
        run: pipenv run pylint *.py **/*.py

      - name: lint the graphql schema
        run: pipenv run strawberry export-schema main | npx graphql-schema-linter -s -e relay-page-info-spec,enum-values-have-descriptions

      - name: test with pytest
        run: pipenv run pytest
