name: API CI

on:
  push:
    branches: [ master ]
    paths:
      - 'api/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'api/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3

      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: install dependencies
        run: npm ci

      - name: install pipenv
        run: pip install pipenv

      - uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4
        with:
          python-version: '3.9'
          cache: 'pipenv'

      - name: install dependencies
        run: pipenv install --dev --deploy

      - name: lint with pylint
        run: pipenv run pylint *.py **/*.py

      - name: lint the graphql schema
        run: pipenv run strawberry export-schema main | npx graphql-schema-linter -s -e relay-page-info-spec,enum-values-have-descriptions

      - name: test with pytest
        run: pipenv run pytest
