name: app CI

on:
  push:
    branches: [ master ]
    paths:
      - 'app/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'app/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app

    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3

      - uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a # tag=v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: install dependencies
        run: npm ci

      - name: lint
        run: npm run lint

      - name: test
        run: npm run test -- run

      - name: compile
        run: npm run build
