name: app CI

on:
  push:
    branches: [ master ]
    paths:
      - 'app/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'app/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app

    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3

      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: install dependencies
        run: npm ci

      - name: lint
        run: npm run lint

      - name: test
        run: npm run test -- run

      - name: compile
        run: npm run build
