name: Release

on:
  push:
    branches: [ master ]
    paths:
      - 'Dockerfile'
      - '.dockerignore'
      - 'api/**'
      - 'app/**'

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2

      - uses: actions/setup-node@f658dc5bd7deff7ab8a4bfa9ccb65a6540175be2
        with:
          node-version: '16'
          cache: 'npm'

      - name: install dependencies
        run: npm ci

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@e94a2173af4c45a258860ad8323bae2080d868d4 # renovate: tag=v3
        with:
          github-token: ${{ secrets.github_token }}
          output-file: "false"
          skip-commit: "true"
          config-file-path: "./changelog.config.js"

      - name: Log in to the Container registry
        uses: docker/login-action@5fcefb941de79536616e9422226e33fd39f1706f
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},value=${{ steps.changelog.outputs.tag }}

      - name: Build and push Docker image
        id: package
        uses: docker/build-push-action@a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229 # renovate: tag=v2
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Create Release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # renovate: tag=v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: |
            Get the image:
            ```
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.changelog.outputs.version }}
            ```

            Run the image:
            ```
            docker run -d -p 8000:80 -v /var/run/docker.sock:/var/run/docker.sock ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.changelog.outputs.version }}
            ```

            ${{ steps.changelog.outputs.clean_changelog }}
